export type ERC721FullFeaturedCollectionConfig = {
  collectionName?: string;
  collectionSymbol?: string;
  collectionDescription?: string;
  collectionImageUri?: string;
  collectionMetadataUri?: string;
  maxSupply?: string;
  placeholderName?: string;
  placeholderDescription?: string;
  placeholderImageUri?: string;
  placeholderMetadataUri?: string;
  preSalePrice?: string;
  preSalePerWallet?: string;
  publicSalePrice?: string;
  publicSalePerTx?: string;
  royaltyAddress?: string;
  royaltyPercent?: string;
  openSeaProxyRegistryAddress?: string;
  openSeaExchangeAddress?: string;
  trustedForwarder?: string;
};
