/* THIS AN AUTO-GENERATED FILE, DO NOT EDIT MANUALLY */
/* eslint-disable */
import { ERC721AutoIdMinterExtension as V1_ERC721AutoIdMinterExtension,
        ERC721AutoIdMinterExtension__factory as V1_ERC721AutoIdMinterExtension__factory
      ,ERC721BulkifyExtension as V1_ERC721BulkifyExtension,
        ERC721BulkifyExtension__factory as V1_ERC721BulkifyExtension__factory
      ,ERC721CollectionMetadataExtension as V1_ERC721CollectionMetadataExtension,
        ERC721CollectionMetadataExtension__factory as V1_ERC721CollectionMetadataExtension__factory
      ,ERC721FreeMintExtension as V1_ERC721FreeMintExtension,
        ERC721FreeMintExtension__factory as V1_ERC721FreeMintExtension__factory
      ,ERC721LockableExtension as V1_ERC721LockableExtension,
        ERC721LockableExtension__factory as V1_ERC721LockableExtension__factory
      ,ERC721OneOfOneMintExtension as V1_ERC721OneOfOneMintExtension,
        ERC721OneOfOneMintExtension__factory as V1_ERC721OneOfOneMintExtension__factory
      ,ERC721OwnerManagedExtension as V1_ERC721OwnerManagedExtension,
        ERC721OwnerManagedExtension__factory as V1_ERC721OwnerManagedExtension__factory
      ,ERC721OwnerMintExtension as V1_ERC721OwnerMintExtension,
        ERC721OwnerMintExtension__factory as V1_ERC721OwnerMintExtension__factory
      ,ERC721PerTokenMetadataExtension as V1_ERC721PerTokenMetadataExtension,
        ERC721PerTokenMetadataExtension__factory as V1_ERC721PerTokenMetadataExtension__factory
      ,ERC721PrefixedMetadataExtension as V1_ERC721PrefixedMetadataExtension,
        ERC721PrefixedMetadataExtension__factory as V1_ERC721PrefixedMetadataExtension__factory
      ,ERC721PreSaleExtension as V1_ERC721PreSaleExtension,
        ERC721PreSaleExtension__factory as V1_ERC721PreSaleExtension__factory
      ,ERC721PublicSaleExtension as V1_ERC721PublicSaleExtension,
        ERC721PublicSaleExtension__factory as V1_ERC721PublicSaleExtension__factory
      ,ERC721RoleBasedLockableExtension as V1_ERC721RoleBasedLockableExtension,
        ERC721RoleBasedLockableExtension__factory as V1_ERC721RoleBasedLockableExtension__factory
      ,ERC721RoleBasedMintExtension as V1_ERC721RoleBasedMintExtension,
        ERC721RoleBasedMintExtension__factory as V1_ERC721RoleBasedMintExtension__factory
      ,ERC721RoyaltyExtension as V1_ERC721RoyaltyExtension,
        ERC721RoyaltyExtension__factory as V1_ERC721RoyaltyExtension__factory
      ,ERC721TieringExtension as V1_ERC721TieringExtension,
        ERC721TieringExtension__factory as V1_ERC721TieringExtension__factory
      ,IERC721AutoIdMinterExtension as V1_IERC721AutoIdMinterExtension,
        IERC721AutoIdMinterExtension__factory as V1_IERC721AutoIdMinterExtension__factory
      ,IERC721BulkifyExtension as V1_IERC721BulkifyExtension,
        IERC721BulkifyExtension__factory as V1_IERC721BulkifyExtension__factory
      ,IERC721CollectionMetadataExtension as V1_IERC721CollectionMetadataExtension,
        IERC721CollectionMetadataExtension__factory as V1_IERC721CollectionMetadataExtension__factory
      ,IERC721FreeMintExtension as V1_IERC721FreeMintExtension,
        IERC721FreeMintExtension__factory as V1_IERC721FreeMintExtension__factory
      ,IERC721LockableExtension as V1_IERC721LockableExtension,
        IERC721LockableExtension__factory as V1_IERC721LockableExtension__factory
      ,IERC721OneOfOneMintExtension as V1_IERC721OneOfOneMintExtension,
        IERC721OneOfOneMintExtension__factory as V1_IERC721OneOfOneMintExtension__factory
      ,IERC721OwnerManagedExtension as V1_IERC721OwnerManagedExtension,
        IERC721OwnerManagedExtension__factory as V1_IERC721OwnerManagedExtension__factory
      ,IERC721OwnerMintExtension as V1_IERC721OwnerMintExtension,
        IERC721OwnerMintExtension__factory as V1_IERC721OwnerMintExtension__factory
      ,IERC721PerTokenMetadataExtension as V1_IERC721PerTokenMetadataExtension,
        IERC721PerTokenMetadataExtension__factory as V1_IERC721PerTokenMetadataExtension__factory
      ,IERC721PrefixedMetadataExtension as V1_IERC721PrefixedMetadataExtension,
        IERC721PrefixedMetadataExtension__factory as V1_IERC721PrefixedMetadataExtension__factory
      ,IERC721PreSaleExtension as V1_IERC721PreSaleExtension,
        IERC721PreSaleExtension__factory as V1_IERC721PreSaleExtension__factory
      ,IERC721PublicSaleExtension as V1_IERC721PublicSaleExtension,
        IERC721PublicSaleExtension__factory as V1_IERC721PublicSaleExtension__factory
      ,IERC721RoleBasedLockableExtension as V1_IERC721RoleBasedLockableExtension,
        IERC721RoleBasedLockableExtension__factory as V1_IERC721RoleBasedLockableExtension__factory
      ,IERC721RoleBasedMintExtension as V1_IERC721RoleBasedMintExtension,
        IERC721RoleBasedMintExtension__factory as V1_IERC721RoleBasedMintExtension__factory
      ,IERC721RoyaltyExtension as V1_IERC721RoyaltyExtension,
        IERC721RoyaltyExtension__factory as V1_IERC721RoyaltyExtension__factory
      ,IERC721TieringExtension as V1_IERC721TieringExtension,
        IERC721TieringExtension__factory as V1_IERC721TieringExtension__factory
      ,ERC721ManagedPrefixedCollection as V1_ERC721ManagedPrefixedCollection,
        ERC721ManagedPrefixedCollection__factory as V1_ERC721ManagedPrefixedCollection__factory
      ,ERC721OneOfOneCollection as V1_ERC721OneOfOneCollection,
        ERC721OneOfOneCollection__factory as V1_ERC721OneOfOneCollection__factory
      ,ERC721SimpleSalesCollection as V1_ERC721SimpleSalesCollection,
        ERC721SimpleSalesCollection__factory as V1_ERC721SimpleSalesCollection__factory
      ,ERC721TieredSalesCollection as V1_ERC721TieredSalesCollection,
        ERC721TieredSalesCollection__factory as V1_ERC721TieredSalesCollection__factory
      ,ERC721ACollectionMetadataExtension as V1_ERC721ACollectionMetadataExtension,
        ERC721ACollectionMetadataExtension__factory as V1_ERC721ACollectionMetadataExtension__factory
      ,ERC721AFreeMintExtension as V1_ERC721AFreeMintExtension,
        ERC721AFreeMintExtension__factory as V1_ERC721AFreeMintExtension__factory
      ,ERC721ALockableExtension as V1_ERC721ALockableExtension,
        ERC721ALockableExtension__factory as V1_ERC721ALockableExtension__factory
      ,ERC721AMinterExtension as V1_ERC721AMinterExtension,
        ERC721AMinterExtension__factory as V1_ERC721AMinterExtension__factory
      ,ERC721AOneOfOneMintExtension as V1_ERC721AOneOfOneMintExtension,
        ERC721AOneOfOneMintExtension__factory as V1_ERC721AOneOfOneMintExtension__factory
      ,ERC721AOwnerManagedExtension as V1_ERC721AOwnerManagedExtension,
        ERC721AOwnerManagedExtension__factory as V1_ERC721AOwnerManagedExtension__factory
      ,ERC721AOwnerMintExtension as V1_ERC721AOwnerMintExtension,
        ERC721AOwnerMintExtension__factory as V1_ERC721AOwnerMintExtension__factory
      ,ERC721APerTokenMetadataExtension as V1_ERC721APerTokenMetadataExtension,
        ERC721APerTokenMetadataExtension__factory as V1_ERC721APerTokenMetadataExtension__factory
      ,ERC721APrefixedMetadataExtension as V1_ERC721APrefixedMetadataExtension,
        ERC721APrefixedMetadataExtension__factory as V1_ERC721APrefixedMetadataExtension__factory
      ,ERC721APreSaleExtension as V1_ERC721APreSaleExtension,
        ERC721APreSaleExtension__factory as V1_ERC721APreSaleExtension__factory
      ,ERC721APublicSaleExtension as V1_ERC721APublicSaleExtension,
        ERC721APublicSaleExtension__factory as V1_ERC721APublicSaleExtension__factory
      ,ERC721ARoleBasedLockableExtension as V1_ERC721ARoleBasedLockableExtension,
        ERC721ARoleBasedLockableExtension__factory as V1_ERC721ARoleBasedLockableExtension__factory
      ,ERC721ARoleBasedMintExtension as V1_ERC721ARoleBasedMintExtension,
        ERC721ARoleBasedMintExtension__factory as V1_ERC721ARoleBasedMintExtension__factory
      ,ERC721ATieringExtension as V1_ERC721ATieringExtension,
        ERC721ATieringExtension__factory as V1_ERC721ATieringExtension__factory
      ,IERC721ALockableExtension as V1_IERC721ALockableExtension,
        IERC721ALockableExtension__factory as V1_IERC721ALockableExtension__factory
      ,IERC721ARoleBasedLockableExtension as V1_IERC721ARoleBasedLockableExtension,
        IERC721ARoleBasedLockableExtension__factory as V1_IERC721ARoleBasedLockableExtension__factory
      ,ERC721AOneOfOneCollection as V1_ERC721AOneOfOneCollection,
        ERC721AOneOfOneCollection__factory as V1_ERC721AOneOfOneCollection__factory
      ,ERC721ASimpleSalesCollection as V1_ERC721ASimpleSalesCollection,
        ERC721ASimpleSalesCollection__factory as V1_ERC721ASimpleSalesCollection__factory
      ,ERC721ATieredSalesCollection as V1_ERC721ATieredSalesCollection,
        ERC721ATieredSalesCollection__factory as V1_ERC721ATieredSalesCollection__factory
      ,ILicenseExtension as V1_ILicenseExtension,
        ILicenseExtension__factory as V1_ILicenseExtension__factory
      ,IWithdrawExtension as V1_IWithdrawExtension,
        IWithdrawExtension__factory as V1_IWithdrawExtension__factory
      ,LicenseExtension as V1_LicenseExtension,
        LicenseExtension__factory as V1_LicenseExtension__factory
      ,ERC2771ContextOwnable as V1_ERC2771ContextOwnable,
        ERC2771ContextOwnable__factory as V1_ERC2771ContextOwnable__factory
      ,UnorderedForwarder as V1_UnorderedForwarder,
        UnorderedForwarder__factory as V1_UnorderedForwarder__factory
      ,WithdrawExtension as V1_WithdrawExtension,
        WithdrawExtension__factory as V1_WithdrawExtension__factory
      ,FlairFactory as V1_FlairFactory,
        FlairFactory__factory as V1_FlairFactory__factory
      ,FlairFactoryNewable as V1_FlairFactoryNewable,
        FlairFactoryNewable__factory as V1_FlairFactoryNewable__factory
      ,MinimalProxy as V1_MinimalProxy,
        MinimalProxy__factory as V1_MinimalProxy__factory
      ,ProxyRegistry as V1_ProxyRegistry,
        ProxyRegistry__factory as V1_ProxyRegistry__factory
      ,NativeMetaTransaction as V1_NativeMetaTransaction,
        NativeMetaTransaction__factory as V1_NativeMetaTransaction__factory
      ,IRoyalties as V1_IRoyalties,
        IRoyalties__factory as V1_IRoyalties__factory
      ,LibPart as V1_LibPart,
        LibPart__factory as V1_LibPart__factory
      ,AccessControl as V1_AccessControl,
        AccessControl__factory as V1_AccessControl__factory
      ,IAccessControl as V1_IAccessControl,
        IAccessControl__factory as V1_IAccessControl__factory
      ,Ownable as V1_Ownable,
        Ownable__factory as V1_Ownable__factory
      ,Proxy as V1_Proxy,
        Proxy__factory as V1_Proxy__factory
      ,Initializable as V1_Initializable,
        Initializable__factory as V1_Initializable__factory
      ,Pausable as V1_Pausable,
        Pausable__factory as V1_Pausable__factory
      ,ERC20 as V1_ERC20,
        ERC20__factory as V1_ERC20__factory
      ,ERC20Burnable as V1_ERC20Burnable,
        ERC20Burnable__factory as V1_ERC20Burnable__factory
      ,IERC20Metadata as V1_IERC20Metadata,
        IERC20Metadata__factory as V1_IERC20Metadata__factory
      ,IERC20 as V1_IERC20,
        IERC20__factory as V1_IERC20__factory
      ,ERC721 as V1_ERC721,
        ERC721__factory as V1_ERC721__factory
      ,ERC721Enumerable as V1_ERC721Enumerable,
        ERC721Enumerable__factory as V1_ERC721Enumerable__factory
      ,ERC721URIStorage as V1_ERC721URIStorage,
        ERC721URIStorage__factory as V1_ERC721URIStorage__factory
      ,IERC721Enumerable as V1_IERC721Enumerable,
        IERC721Enumerable__factory as V1_IERC721Enumerable__factory
      ,IERC721Metadata as V1_IERC721Metadata,
        IERC721Metadata__factory as V1_IERC721Metadata__factory
      ,IERC721 as V1_IERC721,
        IERC721__factory as V1_IERC721__factory
      ,IERC721Receiver as V1_IERC721Receiver,
        IERC721Receiver__factory as V1_IERC721Receiver__factory
      ,ERC165 as V1_ERC165,
        ERC165__factory as V1_ERC165__factory
      ,ERC165Storage as V1_ERC165Storage,
        ERC165Storage__factory as V1_ERC165Storage__factory
      ,IERC165 as V1_IERC165,
        IERC165__factory as V1_IERC165__factory
      ,ERC721MultiTokenStream as V1_ERC721MultiTokenStream,
        ERC721MultiTokenStream__factory as V1_ERC721MultiTokenStream__factory
      ,IERC721MultiTokenStream as V1_IERC721MultiTokenStream,
        IERC721MultiTokenStream__factory as V1_IERC721MultiTokenStream__factory
      ,ERC721CustodialStakingExtension as V1_ERC721CustodialStakingExtension,
        ERC721CustodialStakingExtension__factory as V1_ERC721CustodialStakingExtension__factory
      ,ERC721EmissionReleaseExtension as V1_ERC721EmissionReleaseExtension,
        ERC721EmissionReleaseExtension__factory as V1_ERC721EmissionReleaseExtension__factory
      ,ERC721EqualSplitExtension as V1_ERC721EqualSplitExtension,
        ERC721EqualSplitExtension__factory as V1_ERC721EqualSplitExtension__factory
      ,ERC721InstantReleaseExtension as V1_ERC721InstantReleaseExtension,
        ERC721InstantReleaseExtension__factory as V1_ERC721InstantReleaseExtension__factory
      ,ERC721LockableClaimExtension as V1_ERC721LockableClaimExtension,
        ERC721LockableClaimExtension__factory as V1_ERC721LockableClaimExtension__factory
      ,ERC721LockedStakingExtension as V1_ERC721LockedStakingExtension,
        ERC721LockedStakingExtension__factory as V1_ERC721LockedStakingExtension__factory
      ,ERC721ShareSplitExtension as V1_ERC721ShareSplitExtension,
        ERC721ShareSplitExtension__factory as V1_ERC721ShareSplitExtension__factory
      ,ERC721StakingExtension as V1_ERC721StakingExtension,
        ERC721StakingExtension__factory as V1_ERC721StakingExtension__factory
      ,ERC721VestingReleaseExtension as V1_ERC721VestingReleaseExtension,
        ERC721VestingReleaseExtension__factory as V1_ERC721VestingReleaseExtension__factory
      ,IERC721CustodialStakingExtension as V1_IERC721CustodialStakingExtension,
        IERC721CustodialStakingExtension__factory as V1_IERC721CustodialStakingExtension__factory
      ,IERC721EmissionReleaseExtension as V1_IERC721EmissionReleaseExtension,
        IERC721EmissionReleaseExtension__factory as V1_IERC721EmissionReleaseExtension__factory
      ,IERC721EqualSplitExtension as V1_IERC721EqualSplitExtension,
        IERC721EqualSplitExtension__factory as V1_IERC721EqualSplitExtension__factory
      ,IERC721InstantReleaseExtension as V1_IERC721InstantReleaseExtension,
        IERC721InstantReleaseExtension__factory as V1_IERC721InstantReleaseExtension__factory
      ,IERC721LockableClaimExtension as V1_IERC721LockableClaimExtension,
        IERC721LockableClaimExtension__factory as V1_IERC721LockableClaimExtension__factory
      ,IERC721LockedStakingExtension as V1_IERC721LockedStakingExtension,
        IERC721LockedStakingExtension__factory as V1_IERC721LockedStakingExtension__factory
      ,IERC721ShareSplitExtension as V1_IERC721ShareSplitExtension,
        IERC721ShareSplitExtension__factory as V1_IERC721ShareSplitExtension__factory
      ,IERC721StakingExtension as V1_IERC721StakingExtension,
        IERC721StakingExtension__factory as V1_IERC721StakingExtension__factory
      ,IERC721VestingReleaseExtension as V1_IERC721VestingReleaseExtension,
        IERC721VestingReleaseExtension__factory as V1_IERC721VestingReleaseExtension__factory
      ,ERC721CustodialStakingEmissionStream as V1_ERC721CustodialStakingEmissionStream,
        ERC721CustodialStakingEmissionStream__factory as V1_ERC721CustodialStakingEmissionStream__factory
      ,ERC721EqualEmissionStream as V1_ERC721EqualEmissionStream,
        ERC721EqualEmissionStream__factory as V1_ERC721EqualEmissionStream__factory
      ,ERC721EqualInstantStream as V1_ERC721EqualInstantStream,
        ERC721EqualInstantStream__factory as V1_ERC721EqualInstantStream__factory
      ,ERC721EqualVestingStream as V1_ERC721EqualVestingStream,
        ERC721EqualVestingStream__factory as V1_ERC721EqualVestingStream__factory
      ,ERC721LockedStakingEmissionStream as V1_ERC721LockedStakingEmissionStream,
        ERC721LockedStakingEmissionStream__factory as V1_ERC721LockedStakingEmissionStream__factory
      ,ERC721ShareEmissionStream as V1_ERC721ShareEmissionStream,
        ERC721ShareEmissionStream__factory as V1_ERC721ShareEmissionStream__factory
      ,ERC721ShareInstantStream as V1_ERC721ShareInstantStream,
        ERC721ShareInstantStream__factory as V1_ERC721ShareInstantStream__factory
      ,ERC721ShareVestingStream as V1_ERC721ShareVestingStream,
        ERC721ShareVestingStream__factory as V1_ERC721ShareVestingStream__factory
      ,TestERC20 as V1_TestERC20,
        TestERC20__factory as V1_TestERC20__factory
      ,TestERC721 as V1_TestERC721,
        TestERC721__factory as V1_TestERC721__factory
      ,ERC20RoleBasedLockingExtension as V1_ERC20RoleBasedLockingExtension,
        ERC20RoleBasedLockingExtension__factory as V1_ERC20RoleBasedLockingExtension__factory
      ,ERC20RoleBasedLockingExtensionInterface as V1_ERC20RoleBasedLockingExtensionInterface,
        ERC20RoleBasedLockingExtensionInterface__factory as V1_ERC20RoleBasedLockingExtensionInterface__factory
      ,ERC20BasicToken as V1_ERC20BasicToken,
        ERC20BasicToken__factory as V1_ERC20BasicToken__factory
      ,ERC20LockableToken as V1_ERC20LockableToken,
        ERC20LockableToken__factory as V1_ERC20LockableToken__factory
       } from 'flair-contracts-v1';;import { IERC173 as V2_IERC173,
        IERC173__factory as V2_IERC173__factory
      ,IERC173Events as V2_IERC173Events,
        IERC173Events__factory as V2_IERC173Events__factory
      ,Ownable as V2_Ownable,
        Ownable__factory as V2_Ownable__factory
      ,OwnableERC2771 as V2_OwnableERC2771,
        OwnableERC2771__factory as V2_OwnableERC2771__factory
      ,OwnableInternal as V2_OwnableInternal,
        OwnableInternal__factory as V2_OwnableInternal__factory
      ,AccessControl as V2_AccessControl,
        AccessControl__factory as V2_AccessControl__factory
      ,AccessControlEnumerable as V2_AccessControlEnumerable,
        AccessControlEnumerable__factory as V2_AccessControlEnumerable__factory
      ,AccessControlEnumerableERC2771 as V2_AccessControlEnumerableERC2771,
        AccessControlEnumerableERC2771__factory as V2_AccessControlEnumerableERC2771__factory
      ,AccessControlERC2771 as V2_AccessControlERC2771,
        AccessControlERC2771__factory as V2_AccessControlERC2771__factory
      ,AccessControlInternal as V2_AccessControlInternal,
        AccessControlInternal__factory as V2_AccessControlInternal__factory
      ,IAccessControl as V2_IAccessControl,
        IAccessControl__factory as V2_IAccessControl__factory
      ,IAccessControlEnumerable as V2_IAccessControlEnumerable,
        IAccessControlEnumerable__factory as V2_IAccessControlEnumerable__factory
      ,IAccessControlEvents as V2_IAccessControlEvents,
        IAccessControlEvents__factory as V2_IAccessControlEvents__factory
      ,IWithdrawExtension as V2_IWithdrawExtension,
        IWithdrawExtension__factory as V2_IWithdrawExtension__factory
      ,UnorderedForwarder as V2_UnorderedForwarder,
        UnorderedForwarder__factory as V2_UnorderedForwarder__factory
      ,WithdrawExtension as V2_WithdrawExtension,
        WithdrawExtension__factory as V2_WithdrawExtension__factory
      ,Diamond as V2_Diamond,
        Diamond__factory as V2_Diamond__factory
      ,DiamondCut as V2_DiamondCut,
        DiamondCut__factory as V2_DiamondCut__factory
      ,DiamondLoupe as V2_DiamondLoupe,
        DiamondLoupe__factory as V2_DiamondLoupe__factory
      ,DiamondStorage as V2_DiamondStorage,
        DiamondStorage__factory as V2_DiamondStorage__factory
      ,IDiamondCut as V2_IDiamondCut,
        IDiamondCut__factory as V2_IDiamondCut__factory
      ,IDiamondLoupe as V2_IDiamondLoupe,
        IDiamondLoupe__factory as V2_IDiamondLoupe__factory
      ,FlairFactory as V2_FlairFactory,
        FlairFactory__factory as V2_FlairFactory__factory
      ,FlairFactoryNewable as V2_FlairFactoryNewable,
        FlairFactoryNewable__factory as V2_FlairFactoryNewable__factory
      ,MinimalProxy as V2_MinimalProxy,
        MinimalProxy__factory as V2_MinimalProxy__factory
      ,ITieredSales as V2_ITieredSales,
        ITieredSales__factory as V2_ITieredSales__factory
      ,ITieredSalesAdmin as V2_ITieredSalesAdmin,
        ITieredSalesAdmin__factory as V2_ITieredSalesAdmin__factory
      ,TieredSales as V2_TieredSales,
        TieredSales__factory as V2_TieredSales__factory
      ,TieredSalesERC2771 as V2_TieredSalesERC2771,
        TieredSalesERC2771__factory as V2_TieredSalesERC2771__factory
      ,TieredSalesInternal as V2_TieredSalesInternal,
        TieredSalesInternal__factory as V2_TieredSalesInternal__factory
      ,TieredSalesOwnable as V2_TieredSalesOwnable,
        TieredSalesOwnable__factory as V2_TieredSalesOwnable__factory
      ,ERC165 as V2_ERC165,
        ERC165__factory as V2_ERC165__factory
      ,ERC165Ownable as V2_ERC165Ownable,
        ERC165Ownable__factory as V2_ERC165Ownable__factory
      ,ERC165Storage as V2_ERC165Storage,
        ERC165Storage__factory as V2_ERC165Storage__factory
      ,IERC165 as V2_IERC165,
        IERC165__factory as V2_IERC165__factory
      ,IERC165Admin as V2_IERC165Admin,
        IERC165Admin__factory as V2_IERC165Admin__factory
      ,ERC2771Context as V2_ERC2771Context,
        ERC2771Context__factory as V2_ERC2771Context__factory
      ,ERC2771ContextOwnable as V2_ERC2771ContextOwnable,
        ERC2771ContextOwnable__factory as V2_ERC2771ContextOwnable__factory
      ,IERC2771Context as V2_IERC2771Context,
        IERC2771Context__factory as V2_IERC2771Context__factory
      ,IERC2771ContextAdmin as V2_IERC2771ContextAdmin,
        IERC2771ContextAdmin__factory as V2_IERC2771ContextAdmin__factory
      ,Proxy as V2_Proxy,
        Proxy__factory as V2_Proxy__factory
      ,Initializable as V2_Initializable,
        Initializable__factory as V2_Initializable__factory
      ,ERC1155 as V2_ERC1155,
        ERC1155__factory as V2_ERC1155__factory
      ,ERC1155Burnable as V2_ERC1155Burnable,
        ERC1155Burnable__factory as V2_ERC1155Burnable__factory
      ,ERC1155Supply as V2_ERC1155Supply,
        ERC1155Supply__factory as V2_ERC1155Supply__factory
      ,IERC1155 as V2_IERC1155,
        IERC1155__factory as V2_IERC1155__factory
      ,IERC1155Receiver as V2_IERC1155Receiver,
        IERC1155Receiver__factory as V2_IERC1155Receiver__factory
      ,IERC20 as V2_IERC20,
        IERC20__factory as V2_IERC20__factory
      ,IERC721 as V2_IERC721,
        IERC721__factory as V2_IERC721__factory
      ,Multicall as V2_Multicall,
        Multicall__factory as V2_Multicall__factory
      ,ERC1155Base as V2_ERC1155Base,
        ERC1155Base__factory as V2_ERC1155Base__factory
      ,ERC1155BaseERC2771 as V2_ERC1155BaseERC2771,
        ERC1155BaseERC2771__factory as V2_ERC1155BaseERC2771__factory
      ,ERC1155BaseInternal as V2_ERC1155BaseInternal,
        ERC1155BaseInternal__factory as V2_ERC1155BaseInternal__factory
      ,ERC1155WithERC2771 as V2_ERC1155WithERC2771,
        ERC1155WithERC2771__factory as V2_ERC1155WithERC2771__factory
      ,IERC1155Burnable as V2_IERC1155Burnable,
        IERC1155Burnable__factory as V2_IERC1155Burnable__factory
      ,ERC1155Lockable as V2_ERC1155Lockable,
        ERC1155Lockable__factory as V2_ERC1155Lockable__factory
      ,ERC1155LockableInternal as V2_ERC1155LockableInternal,
        ERC1155LockableInternal__factory as V2_ERC1155LockableInternal__factory
      ,IERC1155Lockable as V2_IERC1155Lockable,
        IERC1155Lockable__factory as V2_IERC1155Lockable__factory
      ,ERC1155Mintable as V2_ERC1155Mintable,
        ERC1155Mintable__factory as V2_ERC1155Mintable__factory
      ,IERC1155Mintable as V2_IERC1155Mintable,
        IERC1155Mintable__factory as V2_IERC1155Mintable__factory
      ,ERC1155SupplyInternal as V2_ERC1155SupplyInternal,
        ERC1155SupplyInternal__factory as V2_ERC1155SupplyInternal__factory
      ,IERC1155Supply as V2_IERC1155Supply,
        IERC1155Supply__factory as V2_IERC1155Supply__factory
      ,ERC1155BurnableOwnable as V2_ERC1155BurnableOwnable,
        ERC1155BurnableOwnable__factory as V2_ERC1155BurnableOwnable__factory
      ,IERC1155BurnableAdmin as V2_IERC1155BurnableAdmin,
        IERC1155BurnableAdmin__factory as V2_IERC1155BurnableAdmin__factory
      ,ERC1155Metadata as V2_ERC1155Metadata,
        ERC1155Metadata__factory as V2_ERC1155Metadata__factory
      ,ERC1155MetadataInternal as V2_ERC1155MetadataInternal,
        ERC1155MetadataInternal__factory as V2_ERC1155MetadataInternal__factory
      ,ERC1155MetadataOwnable as V2_ERC1155MetadataOwnable,
        ERC1155MetadataOwnable__factory as V2_ERC1155MetadataOwnable__factory
      ,IERC1155Metadata as V2_IERC1155Metadata,
        IERC1155Metadata__factory as V2_IERC1155Metadata__factory
      ,IERC1155MetadataAdmin as V2_IERC1155MetadataAdmin,
        IERC1155MetadataAdmin__factory as V2_IERC1155MetadataAdmin__factory
      ,IERC1155MetadataEvents as V2_IERC1155MetadataEvents,
        IERC1155MetadataEvents__factory as V2_IERC1155MetadataEvents__factory
      ,ERC1155MintByOwner as V2_ERC1155MintByOwner,
        ERC1155MintByOwner__factory as V2_ERC1155MintByOwner__factory
      ,ERC1155MintByOwnerERC2771 as V2_ERC1155MintByOwnerERC2771,
        ERC1155MintByOwnerERC2771__factory as V2_ERC1155MintByOwnerERC2771__factory
      ,ERC1155MintByRole as V2_ERC1155MintByRole,
        ERC1155MintByRole__factory as V2_ERC1155MintByRole__factory
      ,ERC1155MintByRoleERC2771 as V2_ERC1155MintByRoleERC2771,
        ERC1155MintByRoleERC2771__factory as V2_ERC1155MintByRoleERC2771__factory
      ,IERC1155MintByOwner as V2_IERC1155MintByOwner,
        IERC1155MintByOwner__factory as V2_IERC1155MintByOwner__factory
      ,IERC1155MintByRole as V2_IERC1155MintByRole,
        IERC1155MintByRole__factory as V2_IERC1155MintByRole__factory
      ,ERC1155TieredSales as V2_ERC1155TieredSales,
        ERC1155TieredSales__factory as V2_ERC1155TieredSales__factory
      ,ERC1155TieredSalesERC2771 as V2_ERC1155TieredSalesERC2771,
        ERC1155TieredSalesERC2771__factory as V2_ERC1155TieredSalesERC2771__factory
      ,ERC1155TieredSalesOwnable as V2_ERC1155TieredSalesOwnable,
        ERC1155TieredSalesOwnable__factory as V2_ERC1155TieredSalesOwnable__factory
      ,IERC1155TieredSalesAdmin as V2_IERC1155TieredSalesAdmin,
        IERC1155TieredSalesAdmin__factory as V2_IERC1155TieredSalesAdmin__factory
      ,ERC1155SupplyOwnable as V2_ERC1155SupplyOwnable,
        ERC1155SupplyOwnable__factory as V2_ERC1155SupplyOwnable__factory
      ,IERC1155SupplyAdmin as V2_IERC1155SupplyAdmin,
        IERC1155SupplyAdmin__factory as V2_IERC1155SupplyAdmin__factory
      ,IERC1155Events as V2_IERC1155Events,
        IERC1155Events__factory as V2_IERC1155Events__factory
       } from 'flair-contracts-v2';

export type { V1_ERC721AutoIdMinterExtension,V1_ERC721BulkifyExtension,V1_ERC721CollectionMetadataExtension,V1_ERC721FreeMintExtension,V1_ERC721LockableExtension,V1_ERC721OneOfOneMintExtension,V1_ERC721OwnerManagedExtension,V1_ERC721OwnerMintExtension,V1_ERC721PerTokenMetadataExtension,V1_ERC721PrefixedMetadataExtension,V1_ERC721PreSaleExtension,V1_ERC721PublicSaleExtension,V1_ERC721RoleBasedLockableExtension,V1_ERC721RoleBasedMintExtension,V1_ERC721RoyaltyExtension,V1_ERC721TieringExtension,V1_IERC721AutoIdMinterExtension,V1_IERC721BulkifyExtension,V1_IERC721CollectionMetadataExtension,V1_IERC721FreeMintExtension,V1_IERC721LockableExtension,V1_IERC721OneOfOneMintExtension,V1_IERC721OwnerManagedExtension,V1_IERC721OwnerMintExtension,V1_IERC721PerTokenMetadataExtension,V1_IERC721PrefixedMetadataExtension,V1_IERC721PreSaleExtension,V1_IERC721PublicSaleExtension,V1_IERC721RoleBasedLockableExtension,V1_IERC721RoleBasedMintExtension,V1_IERC721RoyaltyExtension,V1_IERC721TieringExtension,V1_ERC721ManagedPrefixedCollection,V1_ERC721OneOfOneCollection,V1_ERC721SimpleSalesCollection,V1_ERC721TieredSalesCollection,V1_ERC721ACollectionMetadataExtension,V1_ERC721AFreeMintExtension,V1_ERC721ALockableExtension,V1_ERC721AMinterExtension,V1_ERC721AOneOfOneMintExtension,V1_ERC721AOwnerManagedExtension,V1_ERC721AOwnerMintExtension,V1_ERC721APerTokenMetadataExtension,V1_ERC721APrefixedMetadataExtension,V1_ERC721APreSaleExtension,V1_ERC721APublicSaleExtension,V1_ERC721ARoleBasedLockableExtension,V1_ERC721ARoleBasedMintExtension,V1_ERC721ATieringExtension,V1_IERC721ALockableExtension,V1_IERC721ARoleBasedLockableExtension,V1_ERC721AOneOfOneCollection,V1_ERC721ASimpleSalesCollection,V1_ERC721ATieredSalesCollection,V1_ILicenseExtension,V1_IWithdrawExtension,V1_LicenseExtension,V1_ERC2771ContextOwnable,V1_UnorderedForwarder,V1_WithdrawExtension,V1_FlairFactory,V1_FlairFactoryNewable,V1_MinimalProxy,V1_ProxyRegistry,V1_NativeMetaTransaction,V1_IRoyalties,V1_LibPart,V1_AccessControl,V1_IAccessControl,V1_Ownable,V1_Proxy,V1_Initializable,V1_Pausable,V1_ERC20,V1_ERC20Burnable,V1_IERC20Metadata,V1_IERC20,V1_ERC721,V1_ERC721Enumerable,V1_ERC721URIStorage,V1_IERC721Enumerable,V1_IERC721Metadata,V1_IERC721,V1_IERC721Receiver,V1_ERC165,V1_ERC165Storage,V1_IERC165,V1_ERC721MultiTokenStream,V1_IERC721MultiTokenStream,V1_ERC721CustodialStakingExtension,V1_ERC721EmissionReleaseExtension,V1_ERC721EqualSplitExtension,V1_ERC721InstantReleaseExtension,V1_ERC721LockableClaimExtension,V1_ERC721LockedStakingExtension,V1_ERC721ShareSplitExtension,V1_ERC721StakingExtension,V1_ERC721VestingReleaseExtension,V1_IERC721CustodialStakingExtension,V1_IERC721EmissionReleaseExtension,V1_IERC721EqualSplitExtension,V1_IERC721InstantReleaseExtension,V1_IERC721LockableClaimExtension,V1_IERC721LockedStakingExtension,V1_IERC721ShareSplitExtension,V1_IERC721StakingExtension,V1_IERC721VestingReleaseExtension,V1_ERC721CustodialStakingEmissionStream,V1_ERC721EqualEmissionStream,V1_ERC721EqualInstantStream,V1_ERC721EqualVestingStream,V1_ERC721LockedStakingEmissionStream,V1_ERC721ShareEmissionStream,V1_ERC721ShareInstantStream,V1_ERC721ShareVestingStream,V1_TestERC20,V1_TestERC721,V1_ERC20RoleBasedLockingExtension,V1_ERC20RoleBasedLockingExtensionInterface,V1_ERC20BasicToken,V1_ERC20LockableToken }; export { V1_ERC721AutoIdMinterExtension__factory,V1_ERC721BulkifyExtension__factory,V1_ERC721CollectionMetadataExtension__factory,V1_ERC721FreeMintExtension__factory,V1_ERC721LockableExtension__factory,V1_ERC721OneOfOneMintExtension__factory,V1_ERC721OwnerManagedExtension__factory,V1_ERC721OwnerMintExtension__factory,V1_ERC721PerTokenMetadataExtension__factory,V1_ERC721PrefixedMetadataExtension__factory,V1_ERC721PreSaleExtension__factory,V1_ERC721PublicSaleExtension__factory,V1_ERC721RoleBasedLockableExtension__factory,V1_ERC721RoleBasedMintExtension__factory,V1_ERC721RoyaltyExtension__factory,V1_ERC721TieringExtension__factory,V1_IERC721AutoIdMinterExtension__factory,V1_IERC721BulkifyExtension__factory,V1_IERC721CollectionMetadataExtension__factory,V1_IERC721FreeMintExtension__factory,V1_IERC721LockableExtension__factory,V1_IERC721OneOfOneMintExtension__factory,V1_IERC721OwnerManagedExtension__factory,V1_IERC721OwnerMintExtension__factory,V1_IERC721PerTokenMetadataExtension__factory,V1_IERC721PrefixedMetadataExtension__factory,V1_IERC721PreSaleExtension__factory,V1_IERC721PublicSaleExtension__factory,V1_IERC721RoleBasedLockableExtension__factory,V1_IERC721RoleBasedMintExtension__factory,V1_IERC721RoyaltyExtension__factory,V1_IERC721TieringExtension__factory,V1_ERC721ManagedPrefixedCollection__factory,V1_ERC721OneOfOneCollection__factory,V1_ERC721SimpleSalesCollection__factory,V1_ERC721TieredSalesCollection__factory,V1_ERC721ACollectionMetadataExtension__factory,V1_ERC721AFreeMintExtension__factory,V1_ERC721ALockableExtension__factory,V1_ERC721AMinterExtension__factory,V1_ERC721AOneOfOneMintExtension__factory,V1_ERC721AOwnerManagedExtension__factory,V1_ERC721AOwnerMintExtension__factory,V1_ERC721APerTokenMetadataExtension__factory,V1_ERC721APrefixedMetadataExtension__factory,V1_ERC721APreSaleExtension__factory,V1_ERC721APublicSaleExtension__factory,V1_ERC721ARoleBasedLockableExtension__factory,V1_ERC721ARoleBasedMintExtension__factory,V1_ERC721ATieringExtension__factory,V1_IERC721ALockableExtension__factory,V1_IERC721ARoleBasedLockableExtension__factory,V1_ERC721AOneOfOneCollection__factory,V1_ERC721ASimpleSalesCollection__factory,V1_ERC721ATieredSalesCollection__factory,V1_ILicenseExtension__factory,V1_IWithdrawExtension__factory,V1_LicenseExtension__factory,V1_ERC2771ContextOwnable__factory,V1_UnorderedForwarder__factory,V1_WithdrawExtension__factory,V1_FlairFactory__factory,V1_FlairFactoryNewable__factory,V1_MinimalProxy__factory,V1_ProxyRegistry__factory,V1_NativeMetaTransaction__factory,V1_IRoyalties__factory,V1_LibPart__factory,V1_AccessControl__factory,V1_IAccessControl__factory,V1_Ownable__factory,V1_Proxy__factory,V1_Initializable__factory,V1_Pausable__factory,V1_ERC20__factory,V1_ERC20Burnable__factory,V1_IERC20Metadata__factory,V1_IERC20__factory,V1_ERC721__factory,V1_ERC721Enumerable__factory,V1_ERC721URIStorage__factory,V1_IERC721Enumerable__factory,V1_IERC721Metadata__factory,V1_IERC721__factory,V1_IERC721Receiver__factory,V1_ERC165__factory,V1_ERC165Storage__factory,V1_IERC165__factory,V1_ERC721MultiTokenStream__factory,V1_IERC721MultiTokenStream__factory,V1_ERC721CustodialStakingExtension__factory,V1_ERC721EmissionReleaseExtension__factory,V1_ERC721EqualSplitExtension__factory,V1_ERC721InstantReleaseExtension__factory,V1_ERC721LockableClaimExtension__factory,V1_ERC721LockedStakingExtension__factory,V1_ERC721ShareSplitExtension__factory,V1_ERC721StakingExtension__factory,V1_ERC721VestingReleaseExtension__factory,V1_IERC721CustodialStakingExtension__factory,V1_IERC721EmissionReleaseExtension__factory,V1_IERC721EqualSplitExtension__factory,V1_IERC721InstantReleaseExtension__factory,V1_IERC721LockableClaimExtension__factory,V1_IERC721LockedStakingExtension__factory,V1_IERC721ShareSplitExtension__factory,V1_IERC721StakingExtension__factory,V1_IERC721VestingReleaseExtension__factory,V1_ERC721CustodialStakingEmissionStream__factory,V1_ERC721EqualEmissionStream__factory,V1_ERC721EqualInstantStream__factory,V1_ERC721EqualVestingStream__factory,V1_ERC721LockedStakingEmissionStream__factory,V1_ERC721ShareEmissionStream__factory,V1_ERC721ShareInstantStream__factory,V1_ERC721ShareVestingStream__factory,V1_TestERC20__factory,V1_TestERC721__factory,V1_ERC20RoleBasedLockingExtension__factory,V1_ERC20RoleBasedLockingExtensionInterface__factory,V1_ERC20BasicToken__factory,V1_ERC20LockableToken__factory };;export type { V2_IERC173,V2_IERC173Events,V2_Ownable,V2_OwnableERC2771,V2_OwnableInternal,V2_AccessControl,V2_AccessControlEnumerable,V2_AccessControlEnumerableERC2771,V2_AccessControlERC2771,V2_AccessControlInternal,V2_IAccessControl,V2_IAccessControlEnumerable,V2_IAccessControlEvents,V2_IWithdrawExtension,V2_UnorderedForwarder,V2_WithdrawExtension,V2_Diamond,V2_DiamondCut,V2_DiamondLoupe,V2_DiamondStorage,V2_IDiamondCut,V2_IDiamondLoupe,V2_FlairFactory,V2_FlairFactoryNewable,V2_MinimalProxy,V2_ITieredSales,V2_ITieredSalesAdmin,V2_TieredSales,V2_TieredSalesERC2771,V2_TieredSalesInternal,V2_TieredSalesOwnable,V2_ERC165,V2_ERC165Ownable,V2_ERC165Storage,V2_IERC165,V2_IERC165Admin,V2_ERC2771Context,V2_ERC2771ContextOwnable,V2_IERC2771Context,V2_IERC2771ContextAdmin,V2_Proxy,V2_Initializable,V2_ERC1155,V2_ERC1155Burnable,V2_ERC1155Supply,V2_IERC1155,V2_IERC1155Receiver,V2_IERC20,V2_IERC721,V2_Multicall,V2_ERC1155Base,V2_ERC1155BaseERC2771,V2_ERC1155BaseInternal,V2_ERC1155WithERC2771,V2_IERC1155Burnable,V2_ERC1155Lockable,V2_ERC1155LockableInternal,V2_IERC1155Lockable,V2_ERC1155Mintable,V2_IERC1155Mintable,V2_ERC1155SupplyInternal,V2_IERC1155Supply,V2_ERC1155BurnableOwnable,V2_IERC1155BurnableAdmin,V2_ERC1155Metadata,V2_ERC1155MetadataInternal,V2_ERC1155MetadataOwnable,V2_IERC1155Metadata,V2_IERC1155MetadataAdmin,V2_IERC1155MetadataEvents,V2_ERC1155MintByOwner,V2_ERC1155MintByOwnerERC2771,V2_ERC1155MintByRole,V2_ERC1155MintByRoleERC2771,V2_IERC1155MintByOwner,V2_IERC1155MintByRole,V2_ERC1155TieredSales,V2_ERC1155TieredSalesERC2771,V2_ERC1155TieredSalesOwnable,V2_IERC1155TieredSalesAdmin,V2_ERC1155SupplyOwnable,V2_IERC1155SupplyAdmin,V2_IERC1155Events }; export { V2_IERC173__factory,V2_IERC173Events__factory,V2_Ownable__factory,V2_OwnableERC2771__factory,V2_OwnableInternal__factory,V2_AccessControl__factory,V2_AccessControlEnumerable__factory,V2_AccessControlEnumerableERC2771__factory,V2_AccessControlERC2771__factory,V2_AccessControlInternal__factory,V2_IAccessControl__factory,V2_IAccessControlEnumerable__factory,V2_IAccessControlEvents__factory,V2_IWithdrawExtension__factory,V2_UnorderedForwarder__factory,V2_WithdrawExtension__factory,V2_Diamond__factory,V2_DiamondCut__factory,V2_DiamondLoupe__factory,V2_DiamondStorage__factory,V2_IDiamondCut__factory,V2_IDiamondLoupe__factory,V2_FlairFactory__factory,V2_FlairFactoryNewable__factory,V2_MinimalProxy__factory,V2_ITieredSales__factory,V2_ITieredSalesAdmin__factory,V2_TieredSales__factory,V2_TieredSalesERC2771__factory,V2_TieredSalesInternal__factory,V2_TieredSalesOwnable__factory,V2_ERC165__factory,V2_ERC165Ownable__factory,V2_ERC165Storage__factory,V2_IERC165__factory,V2_IERC165Admin__factory,V2_ERC2771Context__factory,V2_ERC2771ContextOwnable__factory,V2_IERC2771Context__factory,V2_IERC2771ContextAdmin__factory,V2_Proxy__factory,V2_Initializable__factory,V2_ERC1155__factory,V2_ERC1155Burnable__factory,V2_ERC1155Supply__factory,V2_IERC1155__factory,V2_IERC1155Receiver__factory,V2_IERC20__factory,V2_IERC721__factory,V2_Multicall__factory,V2_ERC1155Base__factory,V2_ERC1155BaseERC2771__factory,V2_ERC1155BaseInternal__factory,V2_ERC1155WithERC2771__factory,V2_IERC1155Burnable__factory,V2_ERC1155Lockable__factory,V2_ERC1155LockableInternal__factory,V2_IERC1155Lockable__factory,V2_ERC1155Mintable__factory,V2_IERC1155Mintable__factory,V2_ERC1155SupplyInternal__factory,V2_IERC1155Supply__factory,V2_ERC1155BurnableOwnable__factory,V2_IERC1155BurnableAdmin__factory,V2_ERC1155Metadata__factory,V2_ERC1155MetadataInternal__factory,V2_ERC1155MetadataOwnable__factory,V2_IERC1155Metadata__factory,V2_IERC1155MetadataAdmin__factory,V2_IERC1155MetadataEvents__factory,V2_ERC1155MintByOwner__factory,V2_ERC1155MintByOwnerERC2771__factory,V2_ERC1155MintByRole__factory,V2_ERC1155MintByRoleERC2771__factory,V2_IERC1155MintByOwner__factory,V2_IERC1155MintByRole__factory,V2_ERC1155TieredSales__factory,V2_ERC1155TieredSalesERC2771__factory,V2_ERC1155TieredSalesOwnable__factory,V2_IERC1155TieredSalesAdmin__factory,V2_ERC1155SupplyOwnable__factory,V2_IERC1155SupplyAdmin__factory,V2_IERC1155Events__factory };

export type V1_CONTRACTS = "collections/ERC721/extensions/ERC721AutoIdMinterExtension" | "collections/ERC721/extensions/ERC721BulkifyExtension" | "collections/ERC721/extensions/ERC721CollectionMetadataExtension" | "collections/ERC721/extensions/ERC721FreeMintExtension" | "collections/ERC721/extensions/ERC721LockableExtension" | "collections/ERC721/extensions/ERC721OneOfOneMintExtension" | "collections/ERC721/extensions/ERC721OwnerManagedExtension" | "collections/ERC721/extensions/ERC721OwnerMintExtension" | "collections/ERC721/extensions/ERC721PerTokenMetadataExtension" | "collections/ERC721/extensions/ERC721PrefixedMetadataExtension" | "collections/ERC721/extensions/ERC721PreSaleExtension" | "collections/ERC721/extensions/ERC721PublicSaleExtension" | "collections/ERC721/extensions/ERC721RoleBasedLockableExtension" | "collections/ERC721/extensions/ERC721RoleBasedMintExtension" | "collections/ERC721/extensions/ERC721RoyaltyExtension" | "collections/ERC721/extensions/ERC721TieringExtension" | "collections/ERC721/extensions/IERC721AutoIdMinterExtension" | "collections/ERC721/extensions/IERC721BulkifyExtension" | "collections/ERC721/extensions/IERC721CollectionMetadataExtension" | "collections/ERC721/extensions/IERC721FreeMintExtension" | "collections/ERC721/extensions/IERC721LockableExtension" | "collections/ERC721/extensions/IERC721OneOfOneMintExtension" | "collections/ERC721/extensions/IERC721OwnerManagedExtension" | "collections/ERC721/extensions/IERC721OwnerMintExtension" | "collections/ERC721/extensions/IERC721PerTokenMetadataExtension" | "collections/ERC721/extensions/IERC721PrefixedMetadataExtension" | "collections/ERC721/extensions/IERC721PreSaleExtension" | "collections/ERC721/extensions/IERC721PublicSaleExtension" | "collections/ERC721/extensions/IERC721RoleBasedLockableExtension" | "collections/ERC721/extensions/IERC721RoleBasedMintExtension" | "collections/ERC721/extensions/IERC721RoyaltyExtension" | "collections/ERC721/extensions/IERC721TieringExtension" | "collections/ERC721/presets/ERC721ManagedPrefixedCollection" | "collections/ERC721/presets/ERC721OneOfOneCollection" | "collections/ERC721/presets/ERC721SimpleSalesCollection" | "collections/ERC721/presets/ERC721TieredSalesCollection" | "collections/ERC721A/extensions/ERC721ACollectionMetadataExtension" | "collections/ERC721A/extensions/ERC721AFreeMintExtension" | "collections/ERC721A/extensions/ERC721ALockableExtension" | "collections/ERC721A/extensions/ERC721AMinterExtension" | "collections/ERC721A/extensions/ERC721AOneOfOneMintExtension" | "collections/ERC721A/extensions/ERC721AOwnerManagedExtension" | "collections/ERC721A/extensions/ERC721AOwnerMintExtension" | "collections/ERC721A/extensions/ERC721APerTokenMetadataExtension" | "collections/ERC721A/extensions/ERC721APrefixedMetadataExtension" | "collections/ERC721A/extensions/ERC721APreSaleExtension" | "collections/ERC721A/extensions/ERC721APublicSaleExtension" | "collections/ERC721A/extensions/ERC721ARoleBasedLockableExtension" | "collections/ERC721A/extensions/ERC721ARoleBasedMintExtension" | "collections/ERC721A/extensions/ERC721ATieringExtension" | "collections/ERC721A/extensions/IERC721ALockableExtension" | "collections/ERC721A/extensions/IERC721ARoleBasedLockableExtension" | "collections/ERC721A/presets/ERC721AOneOfOneCollection" | "collections/ERC721A/presets/ERC721ASimpleSalesCollection" | "collections/ERC721A/presets/ERC721ATieredSalesCollection" | "common/ILicenseExtension" | "common/IWithdrawExtension" | "common/LicenseExtension" | "common/meta-transactions/ERC2771ContextOwnable" | "common/meta-transactions/UnorderedForwarder" | "common/WithdrawExtension" | "factory/Clones" | "factory/FlairFactory" | "factory/FlairFactoryNewable" | "factory/MinimalProxy" | "misc/opensea/OwnableDelegateProxy" | "misc/opensea/ProxyRegistry" | "misc/polygon/NativeMetaTransaction" | "misc/rarible/IRoyalties" | "misc/rarible/LibPart" | "misc/rarible/LibRoyaltiesV2" | "openzeppelin/access/AccessControl" | "openzeppelin/access/AccessControlCrossChain" | "openzeppelin/access/AccessControlEnumerable" | "openzeppelin/access/IAccessControl" | "openzeppelin/access/IAccessControlEnumerable" | "openzeppelin/access/Ownable" | "openzeppelin/crosschain/amb/CrossChainEnabledAMB" | "openzeppelin/crosschain/amb/LibAMB" | "openzeppelin/crosschain/arbitrum/CrossChainEnabledArbitrumL1" | "openzeppelin/crosschain/arbitrum/CrossChainEnabledArbitrumL2" | "openzeppelin/crosschain/arbitrum/LibArbitrumL1" | "openzeppelin/crosschain/arbitrum/LibArbitrumL2" | "openzeppelin/crosschain/CrossChainEnabled" | "openzeppelin/crosschain/optimism/CrossChainEnabledOptimism" | "openzeppelin/crosschain/optimism/LibOptimism" | "openzeppelin/crosschain/polygon/CrossChainEnabledPolygonChild" | "openzeppelin/finance/PaymentSplitter" | "openzeppelin/finance/VestingWallet" | "openzeppelin/governance/compatibility/GovernorCompatibilityBravo" | "openzeppelin/governance/compatibility/IGovernorCompatibilityBravo" | "openzeppelin/governance/extensions/GovernorCountingSimple" | "openzeppelin/governance/extensions/GovernorPreventLateQuorum" | "openzeppelin/governance/extensions/GovernorProposalThreshold" | "openzeppelin/governance/extensions/GovernorSettings" | "openzeppelin/governance/extensions/GovernorTimelockCompound" | "openzeppelin/governance/extensions/GovernorTimelockControl" | "openzeppelin/governance/extensions/GovernorVotes" | "openzeppelin/governance/extensions/GovernorVotesComp" | "openzeppelin/governance/extensions/GovernorVotesQuorumFraction" | "openzeppelin/governance/extensions/IGovernorTimelock" | "openzeppelin/governance/Governor" | "openzeppelin/governance/IGovernor" | "openzeppelin/governance/TimelockController" | "openzeppelin/governance/utils/IVotes" | "openzeppelin/governance/utils/Votes" | "openzeppelin/interfaces/IERC1822Proxiable" | "openzeppelin/interfaces/IERC2612" | "openzeppelin/interfaces/IERC1271" | "openzeppelin/interfaces/IERC1363" | "openzeppelin/interfaces/IERC1363Receiver" | "openzeppelin/interfaces/IERC1363Spender" | "openzeppelin/interfaces/IERC2981" | "openzeppelin/interfaces/IERC3156FlashBorrower" | "openzeppelin/interfaces/IERC3156FlashLender" | "openzeppelin/interfaces/IERC4626" | "openzeppelin/metatx/ERC2771Context" | "openzeppelin/metatx/MinimalForwarder" | "openzeppelin/proxy/beacon/BeaconProxy" | "openzeppelin/proxy/beacon/IBeacon" | "openzeppelin/proxy/beacon/UpgradeableBeacon" | "openzeppelin/proxy/Clones" | "openzeppelin/proxy/ERC1967/ERC1967Proxy" | "openzeppelin/proxy/ERC1967/ERC1967Upgrade" | "openzeppelin/proxy/Proxy" | "openzeppelin/proxy/transparent/ProxyAdmin" | "openzeppelin/proxy/transparent/TransparentUpgradeableProxy" | "openzeppelin/proxy/utils/Initializable" | "openzeppelin/proxy/utils/UUPSUpgradeable" | "openzeppelin/security/Pausable" | "openzeppelin/security/PullPayment" | "openzeppelin/security/ReentrancyGuard" | "openzeppelin/token/common/ERC2981" | "openzeppelin/token/ERC1155/ERC1155" | "openzeppelin/token/ERC1155/extensions/ERC1155Burnable" | "openzeppelin/token/ERC1155/extensions/ERC1155Pausable" | "openzeppelin/token/ERC1155/extensions/ERC1155Supply" | "openzeppelin/token/ERC1155/extensions/ERC1155URIStorage" | "openzeppelin/token/ERC1155/extensions/IERC1155MetadataURI" | "openzeppelin/token/ERC1155/IERC1155" | "openzeppelin/token/ERC1155/IERC1155Receiver" | "openzeppelin/token/ERC1155/presets/ERC1155PresetMinterPauser" | "openzeppelin/token/ERC1155/utils/ERC1155Holder" | "openzeppelin/token/ERC1155/utils/ERC1155Receiver" | "openzeppelin/token/ERC20/ERC20" | "openzeppelin/token/ERC20/extensions/ERC20Permit" | "openzeppelin/token/ERC20/extensions/IERC20Permit" | "openzeppelin/token/ERC20/extensions/ERC20Burnable" | "openzeppelin/token/ERC20/extensions/ERC20Capped" | "openzeppelin/token/ERC20/extensions/ERC20FlashMint" | "openzeppelin/token/ERC20/extensions/ERC20Pausable" | "openzeppelin/token/ERC20/extensions/ERC20Snapshot" | "openzeppelin/token/ERC20/extensions/ERC20Votes" | "openzeppelin/token/ERC20/extensions/ERC20VotesComp" | "openzeppelin/token/ERC20/extensions/ERC20Wrapper" | "openzeppelin/token/ERC20/extensions/ERC4626" | "openzeppelin/token/ERC20/extensions/IERC20Metadata" | "openzeppelin/token/ERC20/IERC20" | "openzeppelin/token/ERC20/presets/ERC20PresetFixedSupply" | "openzeppelin/token/ERC20/presets/ERC20PresetMinterPauser" | "openzeppelin/token/ERC20/utils/SafeERC20" | "openzeppelin/token/ERC20/utils/TokenTimelock" | "openzeppelin/token/ERC721/ERC721" | "openzeppelin/token/ERC721/extensions/ERC721Votes" | "openzeppelin/token/ERC721/extensions/ERC721Burnable" | "openzeppelin/token/ERC721/extensions/ERC721Enumerable" | "openzeppelin/token/ERC721/extensions/ERC721Pausable" | "openzeppelin/token/ERC721/extensions/ERC721Royalty" | "openzeppelin/token/ERC721/extensions/ERC721URIStorage" | "openzeppelin/token/ERC721/extensions/IERC721Enumerable" | "openzeppelin/token/ERC721/extensions/IERC721Metadata" | "openzeppelin/token/ERC721/IERC721" | "openzeppelin/token/ERC721/IERC721Receiver" | "openzeppelin/token/ERC721/presets/ERC721PresetMinterPauserAutoId" | "openzeppelin/token/ERC721/utils/ERC721Holder" | "openzeppelin/token/ERC777/ERC777" | "openzeppelin/token/ERC777/IERC777" | "openzeppelin/token/ERC777/IERC777Recipient" | "openzeppelin/token/ERC777/IERC777Sender" | "openzeppelin/token/ERC777/presets/ERC777PresetFixedSupply" | "openzeppelin/utils/Address" | "openzeppelin/utils/Arrays" | "openzeppelin/utils/Base64" | "openzeppelin/utils/Checkpoints" | "openzeppelin/utils/Context" | "openzeppelin/utils/Counters" | "openzeppelin/utils/Create2" | "openzeppelin/utils/cryptography/EIP712" | "openzeppelin/utils/cryptography/ECDSA" | "openzeppelin/utils/cryptography/MerkleProof" | "openzeppelin/utils/cryptography/SignatureChecker" | "openzeppelin/utils/escrow/ConditionalEscrow" | "openzeppelin/utils/escrow/Escrow" | "openzeppelin/utils/escrow/RefundEscrow" | "openzeppelin/utils/introspection/ERC165" | "openzeppelin/utils/introspection/ERC165Checker" | "openzeppelin/utils/introspection/ERC165Storage" | "openzeppelin/utils/introspection/ERC1820Implementer" | "openzeppelin/utils/introspection/IERC165" | "openzeppelin/utils/introspection/IERC1820Implementer" | "openzeppelin/utils/introspection/IERC1820Registry" | "openzeppelin/utils/math/Math" | "openzeppelin/utils/math/SafeCast" | "openzeppelin/utils/math/SafeMath" | "openzeppelin/utils/math/SignedMath" | "openzeppelin/utils/math/SignedSafeMath" | "openzeppelin/utils/Multicall" | "openzeppelin/utils/StorageSlot" | "openzeppelin/utils/Strings" | "openzeppelin/utils/structs/BitMaps" | "openzeppelin/utils/structs/DoubleEndedQueue" | "openzeppelin/utils/structs/EnumerableMap" | "openzeppelin/utils/structs/EnumerableSet" | "openzeppelin/utils/Timers" | "openzeppelin/vendor/amb/IAMB" | "openzeppelin/vendor/arbitrum/IArbSys" | "openzeppelin/vendor/arbitrum/IBridge" | "openzeppelin/vendor/arbitrum/IInbox" | "openzeppelin/vendor/arbitrum/IMessageProvider" | "openzeppelin/vendor/arbitrum/IOutbox" | "openzeppelin/vendor/compound/ICompoundTimelock" | "openzeppelin/vendor/optimism/ICrossDomainMessenger" | "openzeppelin/vendor/polygon/IFxMessageProcessor" | "streams/ERC721/base/ERC721MultiTokenStream" | "streams/ERC721/base/IERC721MultiTokenStream" | "streams/ERC721/extensions/ERC721CustodialStakingExtension" | "streams/ERC721/extensions/ERC721EmissionReleaseExtension" | "streams/ERC721/extensions/ERC721EqualSplitExtension" | "streams/ERC721/extensions/ERC721InstantReleaseExtension" | "streams/ERC721/extensions/ERC721LockableClaimExtension" | "streams/ERC721/extensions/ERC721LockedStakingExtension" | "streams/ERC721/extensions/ERC721ShareSplitExtension" | "streams/ERC721/extensions/ERC721StakingExtension" | "streams/ERC721/extensions/ERC721VestingReleaseExtension" | "streams/ERC721/extensions/IERC721CustodialStakingExtension" | "streams/ERC721/extensions/IERC721EmissionReleaseExtension" | "streams/ERC721/extensions/IERC721EqualSplitExtension" | "streams/ERC721/extensions/IERC721InstantReleaseExtension" | "streams/ERC721/extensions/IERC721LockableClaimExtension" | "streams/ERC721/extensions/IERC721LockedStakingExtension" | "streams/ERC721/extensions/IERC721ShareSplitExtension" | "streams/ERC721/extensions/IERC721StakingExtension" | "streams/ERC721/extensions/IERC721VestingReleaseExtension" | "streams/ERC721/presets/ERC721CustodialStakingEmissionStream" | "streams/ERC721/presets/ERC721EqualEmissionStream" | "streams/ERC721/presets/ERC721EqualInstantStream" | "streams/ERC721/presets/ERC721EqualVestingStream" | "streams/ERC721/presets/ERC721LockedStakingEmissionStream" | "streams/ERC721/presets/ERC721ShareEmissionStream" | "streams/ERC721/presets/ERC721ShareInstantStream" | "streams/ERC721/presets/ERC721ShareVestingStream" | "test/TestERC20" | "test/TestERC721" | "tokens/extensions/ERC20RoleBasedLockingExtension" | "tokens/extensions/ERC20RoleBasedLockingExtensionInterface" | "tokens/presets/ERC20BasicToken" | "tokens/presets/ERC20LockableToken";
export type V2_CONTRACTS = "access/ownable/IERC173" | "access/ownable/IERC173Events" | "access/ownable/Ownable" | "access/ownable/OwnableERC2771" | "access/ownable/OwnableInternal" | "access/ownable/OwnableStorage" | "access/roles/AccessControl" | "access/roles/AccessControlEnumerable" | "access/roles/AccessControlEnumerableERC2771" | "access/roles/AccessControlEnumerableStorage" | "access/roles/AccessControlERC2771" | "access/roles/AccessControlInternal" | "access/roles/AccessControlStorage" | "access/roles/IAccessControl" | "access/roles/IAccessControlEnumerable" | "access/roles/IAccessControlEvents" | "common/IWithdrawExtension" | "common/UnorderedForwarder" | "common/WithdrawExtension" | "diamond/Diamond" | "diamond/DiamondCut" | "diamond/DiamondLoupe" | "diamond/DiamondStorage" | "diamond/IDiamondCut" | "diamond/IDiamondLoupe" | "factory/Clones" | "factory/FlairFactory" | "factory/FlairFactoryNewable" | "factory/MinimalProxy" | "finance/sales/ITieredSales" | "finance/sales/ITieredSalesAdmin" | "finance/sales/ITieredSalesInternal" | "finance/sales/TieredSales" | "finance/sales/TieredSalesERC2771" | "finance/sales/TieredSalesInternal" | "finance/sales/TieredSalesOwnable" | "finance/sales/TieredSalesStorage" | "introspection/ERC165" | "introspection/ERC165Ownable" | "introspection/ERC165Storage" | "introspection/IERC165" | "introspection/IERC165Admin" | "metatx/ERC2771Context" | "metatx/ERC2771ContextInternal" | "metatx/ERC2771ContextOwnable" | "metatx/ERC2771ContextStorage" | "metatx/IERC2771Context" | "metatx/IERC2771ContextAdmin" | "openzeppelin/access/AccessControl" | "openzeppelin/access/AccessControlCrossChain" | "openzeppelin/access/AccessControlEnumerable" | "openzeppelin/access/IAccessControl" | "openzeppelin/access/IAccessControlEnumerable" | "openzeppelin/access/Ownable" | "openzeppelin/crosschain/amb/CrossChainEnabledAMB" | "openzeppelin/crosschain/amb/LibAMB" | "openzeppelin/crosschain/arbitrum/CrossChainEnabledArbitrumL1" | "openzeppelin/crosschain/arbitrum/CrossChainEnabledArbitrumL2" | "openzeppelin/crosschain/arbitrum/LibArbitrumL1" | "openzeppelin/crosschain/arbitrum/LibArbitrumL2" | "openzeppelin/crosschain/CrossChainEnabled" | "openzeppelin/crosschain/optimism/CrossChainEnabledOptimism" | "openzeppelin/crosschain/optimism/LibOptimism" | "openzeppelin/crosschain/polygon/CrossChainEnabledPolygonChild" | "openzeppelin/finance/PaymentSplitter" | "openzeppelin/finance/VestingWallet" | "openzeppelin/governance/compatibility/GovernorCompatibilityBravo" | "openzeppelin/governance/compatibility/IGovernorCompatibilityBravo" | "openzeppelin/governance/extensions/GovernorCountingSimple" | "openzeppelin/governance/extensions/GovernorPreventLateQuorum" | "openzeppelin/governance/extensions/GovernorProposalThreshold" | "openzeppelin/governance/extensions/GovernorSettings" | "openzeppelin/governance/extensions/GovernorTimelockCompound" | "openzeppelin/governance/extensions/GovernorTimelockControl" | "openzeppelin/governance/extensions/GovernorVotes" | "openzeppelin/governance/extensions/GovernorVotesComp" | "openzeppelin/governance/extensions/GovernorVotesQuorumFraction" | "openzeppelin/governance/extensions/IGovernorTimelock" | "openzeppelin/governance/Governor" | "openzeppelin/governance/IGovernor" | "openzeppelin/governance/TimelockController" | "openzeppelin/governance/utils/IVotes" | "openzeppelin/governance/utils/Votes" | "openzeppelin/interfaces/IERC1822Proxiable" | "openzeppelin/interfaces/IERC2612" | "openzeppelin/interfaces/IERC1271" | "openzeppelin/interfaces/IERC1363" | "openzeppelin/interfaces/IERC1363Receiver" | "openzeppelin/interfaces/IERC1363Spender" | "openzeppelin/interfaces/IERC2981" | "openzeppelin/interfaces/IERC3156FlashBorrower" | "openzeppelin/interfaces/IERC3156FlashLender" | "openzeppelin/interfaces/IERC4626" | "openzeppelin/metatx/ERC2771Context" | "openzeppelin/metatx/MinimalForwarder" | "openzeppelin/proxy/beacon/BeaconProxy" | "openzeppelin/proxy/beacon/IBeacon" | "openzeppelin/proxy/beacon/UpgradeableBeacon" | "openzeppelin/proxy/Clones" | "openzeppelin/proxy/ERC1967/ERC1967Proxy" | "openzeppelin/proxy/ERC1967/ERC1967Upgrade" | "openzeppelin/proxy/Proxy" | "openzeppelin/proxy/transparent/ProxyAdmin" | "openzeppelin/proxy/transparent/TransparentUpgradeableProxy" | "openzeppelin/proxy/utils/Initializable" | "openzeppelin/proxy/utils/UUPSUpgradeable" | "openzeppelin/security/Pausable" | "openzeppelin/security/PullPayment" | "openzeppelin/security/ReentrancyGuard" | "openzeppelin/token/common/ERC2981" | "openzeppelin/token/ERC1155/ERC1155" | "openzeppelin/token/ERC1155/extensions/ERC1155Burnable" | "openzeppelin/token/ERC1155/extensions/ERC1155Pausable" | "openzeppelin/token/ERC1155/extensions/ERC1155Supply" | "openzeppelin/token/ERC1155/extensions/ERC1155URIStorage" | "openzeppelin/token/ERC1155/extensions/IERC1155MetadataURI" | "openzeppelin/token/ERC1155/IERC1155" | "openzeppelin/token/ERC1155/IERC1155Receiver" | "openzeppelin/token/ERC1155/presets/ERC1155PresetMinterPauser" | "openzeppelin/token/ERC1155/utils/ERC1155Holder" | "openzeppelin/token/ERC1155/utils/ERC1155Receiver" | "openzeppelin/token/ERC20/ERC20" | "openzeppelin/token/ERC20/extensions/ERC20Permit" | "openzeppelin/token/ERC20/extensions/IERC20Permit" | "openzeppelin/token/ERC20/extensions/ERC20Burnable" | "openzeppelin/token/ERC20/extensions/ERC20Capped" | "openzeppelin/token/ERC20/extensions/ERC20FlashMint" | "openzeppelin/token/ERC20/extensions/ERC20Pausable" | "openzeppelin/token/ERC20/extensions/ERC20Snapshot" | "openzeppelin/token/ERC20/extensions/ERC20Votes" | "openzeppelin/token/ERC20/extensions/ERC20VotesComp" | "openzeppelin/token/ERC20/extensions/ERC20Wrapper" | "openzeppelin/token/ERC20/extensions/ERC4626" | "openzeppelin/token/ERC20/extensions/IERC20Metadata" | "openzeppelin/token/ERC20/IERC20" | "openzeppelin/token/ERC20/presets/ERC20PresetFixedSupply" | "openzeppelin/token/ERC20/presets/ERC20PresetMinterPauser" | "openzeppelin/token/ERC20/utils/SafeERC20" | "openzeppelin/token/ERC20/utils/TokenTimelock" | "openzeppelin/token/ERC721/ERC721" | "openzeppelin/token/ERC721/extensions/ERC721Votes" | "openzeppelin/token/ERC721/extensions/ERC721Burnable" | "openzeppelin/token/ERC721/extensions/ERC721Enumerable" | "openzeppelin/token/ERC721/extensions/ERC721Pausable" | "openzeppelin/token/ERC721/extensions/ERC721Royalty" | "openzeppelin/token/ERC721/extensions/ERC721URIStorage" | "openzeppelin/token/ERC721/extensions/IERC721Enumerable" | "openzeppelin/token/ERC721/extensions/IERC721Metadata" | "openzeppelin/token/ERC721/IERC721" | "openzeppelin/token/ERC721/IERC721Receiver" | "openzeppelin/token/ERC721/presets/ERC721PresetMinterPauserAutoId" | "openzeppelin/token/ERC721/utils/ERC721Holder" | "openzeppelin/token/ERC777/ERC777" | "openzeppelin/token/ERC777/IERC777" | "openzeppelin/token/ERC777/IERC777Recipient" | "openzeppelin/token/ERC777/IERC777Sender" | "openzeppelin/token/ERC777/presets/ERC777PresetFixedSupply" | "openzeppelin/utils/Address" | "openzeppelin/utils/Arrays" | "openzeppelin/utils/Base64" | "openzeppelin/utils/Checkpoints" | "openzeppelin/utils/Context" | "openzeppelin/utils/Counters" | "openzeppelin/utils/Create2" | "openzeppelin/utils/cryptography/EIP712" | "openzeppelin/utils/cryptography/ECDSA" | "openzeppelin/utils/cryptography/MerkleProof" | "openzeppelin/utils/cryptography/SignatureChecker" | "openzeppelin/utils/escrow/ConditionalEscrow" | "openzeppelin/utils/escrow/Escrow" | "openzeppelin/utils/escrow/RefundEscrow" | "openzeppelin/utils/introspection/ERC165" | "openzeppelin/utils/introspection/ERC165Checker" | "openzeppelin/utils/introspection/ERC165Storage" | "openzeppelin/utils/introspection/ERC1820Implementer" | "openzeppelin/utils/introspection/IERC165" | "openzeppelin/utils/introspection/IERC1820Implementer" | "openzeppelin/utils/introspection/IERC1820Registry" | "openzeppelin/utils/math/Math" | "openzeppelin/utils/math/SafeCast" | "openzeppelin/utils/math/SafeMath" | "openzeppelin/utils/math/SignedMath" | "openzeppelin/utils/math/SignedSafeMath" | "openzeppelin/utils/Multicall" | "openzeppelin/utils/StorageSlot" | "openzeppelin/utils/Strings" | "openzeppelin/utils/structs/BitMaps" | "openzeppelin/utils/structs/DoubleEndedQueue" | "openzeppelin/utils/structs/EnumerableMap" | "openzeppelin/utils/structs/EnumerableSet" | "openzeppelin/utils/Timers" | "openzeppelin/vendor/amb/IAMB" | "openzeppelin/vendor/arbitrum/IArbSys" | "openzeppelin/vendor/arbitrum/IBridge" | "openzeppelin/vendor/arbitrum/IInbox" | "openzeppelin/vendor/arbitrum/IMessageProvider" | "openzeppelin/vendor/arbitrum/IOutbox" | "openzeppelin/vendor/compound/ICompoundTimelock" | "openzeppelin/vendor/optimism/ICrossDomainMessenger" | "openzeppelin/vendor/polygon/IFxMessageProcessor" | "token/ERC1155/base/ERC1155Base" | "token/ERC1155/base/ERC1155BaseERC2771" | "token/ERC1155/base/ERC1155BaseInternal" | "token/ERC1155/base/ERC1155BaseStorage" | "token/ERC1155/ERC1155" | "token/ERC1155/ERC1155WithERC2771" | "token/ERC1155/extensions/burnable/ERC1155Burnable" | "token/ERC1155/extensions/burnable/ERC1155BurnableStorage" | "token/ERC1155/extensions/burnable/IERC1155Burnable" | "token/ERC1155/extensions/lockable/ERC1155Lockable" | "token/ERC1155/extensions/lockable/ERC1155LockableInternal" | "token/ERC1155/extensions/lockable/ERC1155LockableStorage" | "token/ERC1155/extensions/lockable/IERC1155Lockable" | "token/ERC1155/extensions/mintable/ERC1155Mintable" | "token/ERC1155/extensions/mintable/IERC1155Mintable" | "token/ERC1155/extensions/supply/ERC1155Supply" | "token/ERC1155/extensions/supply/ERC1155SupplyInternal" | "token/ERC1155/extensions/supply/ERC1155SupplyStorage" | "token/ERC1155/extensions/supply/IERC1155Supply" | "token/ERC1155/facets/burnable/ERC1155BurnableOwnable" | "token/ERC1155/facets/burnable/IERC1155BurnableAdmin" | "token/ERC1155/facets/metadata/ERC1155Metadata" | "token/ERC1155/facets/metadata/ERC1155MetadataInternal" | "token/ERC1155/facets/metadata/ERC1155MetadataOwnable" | "token/ERC1155/facets/metadata/ERC1155MetadataStorage" | "token/ERC1155/facets/metadata/IERC1155Metadata" | "token/ERC1155/facets/metadata/IERC1155MetadataAdmin" | "token/ERC1155/facets/metadata/IERC1155MetadataEvents" | "token/ERC1155/facets/minting/ERC1155MintByOwner" | "token/ERC1155/facets/minting/ERC1155MintByOwnerERC2771" | "token/ERC1155/facets/minting/ERC1155MintByRole" | "token/ERC1155/facets/minting/ERC1155MintByRoleERC2771" | "token/ERC1155/facets/minting/IERC1155MintByOwner" | "token/ERC1155/facets/minting/IERC1155MintByRole" | "token/ERC1155/facets/sales/ERC1155TieredSales" | "token/ERC1155/facets/sales/ERC1155TieredSalesERC2771" | "token/ERC1155/facets/sales/ERC1155TieredSalesOwnable" | "token/ERC1155/facets/sales/ERC1155TieredSalesStorage" | "token/ERC1155/facets/sales/IERC1155TieredSalesAdmin" | "token/ERC1155/facets/supply/ERC1155SupplyOwnable" | "token/ERC1155/facets/supply/IERC1155SupplyAdmin" | "token/ERC1155/IERC1155" | "token/ERC1155/IERC1155Events" | "token/ERC1155/IERC1155Receiver";

export type ContractFqn = V1_CONTRACTS | V2_CONTRACTS;

export type ContractVersion = "v1" | "v2";

export const LATEST_VERSION: ContractVersion = "v2";
