export type Version = 'v1.4';

export const LATEST_VERSION = 'v1.4';

export type ContractKey =
  | 'collections/ERC721/extensions/ERC721AutoIdMinterExtension'
  | 'collections/ERC721/extensions/ERC721BulkifyExtension'
  | 'collections/ERC721/extensions/ERC721CollectionMetadataExtension'
  | 'collections/ERC721/extensions/ERC721FreeMintExtension'
  | 'collections/ERC721/extensions/ERC721OneOfOneMintExtension'
  | 'collections/ERC721/extensions/ERC721OpenSeaNoGasWyvernExtension'
  | 'collections/ERC721/extensions/ERC721OpenSeaNoGasZeroExExtension'
  | 'collections/ERC721/extensions/ERC721OwnerMintExtension'
  | 'collections/ERC721/extensions/ERC721PerTokenMetadataExtension'
  | 'collections/ERC721/extensions/ERC721PrefixedMetadataExtension'
  | 'collections/ERC721/extensions/ERC721PreSaleExtension'
  | 'collections/ERC721/extensions/ERC721PublicSaleExtension'
  | 'collections/ERC721/extensions/ERC721RoleBasedMintExtension'
  | 'collections/ERC721/extensions/ERC721RoyaltyExtension'
  | 'collections/ERC721/extensions/ERC721SimpleProceedsExtension'
  | 'collections/ERC721/presets/ERC721FullFeaturedCollection'
  | 'collections/ERC721/presets/ERC721FullFeaturedCollectionWyvern'
  | 'collections/ERC721/presets/ERC721FullFeaturedCollectionZeroEx'
  | 'collections/ERC721/presets/ERC721SimpleCollection'
  | 'misc/opensea/OwnableDelegateProxy'
  | 'misc/opensea/ProxyRegistry'
  | 'misc/polygon/NativeMetaTransaction'
  | 'misc/rarible/IRoyalties'
  | 'misc/rarible/LibPart'
  | 'misc/rarible/LibRoyaltiesV2'
  | 'openzeppelin/access/AccessControl'
  | 'openzeppelin/access/IAccessControl'
  | 'openzeppelin/access/Ownable'
  | 'openzeppelin/security/ReentrancyGuard'
  | 'openzeppelin/token/ERC721/ERC721'
  | 'openzeppelin/token/ERC721/extensions/ERC721URIStorage'
  | 'openzeppelin/token/ERC721/extensions/IERC721Metadata'
  | 'openzeppelin/token/ERC721/IERC721'
  | 'openzeppelin/token/ERC721/IERC721Receiver'
  | 'openzeppelin/utils/Address'
  | 'openzeppelin/utils/Context'
  | 'openzeppelin/utils/cryptography/ECDSA'
  | 'openzeppelin/utils/cryptography/EIP712'
  | 'openzeppelin/utils/cryptography/MerkleProof'
  | 'openzeppelin/utils/introspection/ERC165'
  | 'openzeppelin/utils/introspection/IERC165'
  | 'openzeppelin/utils/math/SafeMath'
  | 'openzeppelin/utils/Strings'
  | 'openzeppelin/utils/structs/EnumerableSet';
