name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build packages
        run: npm run build
        shell: bash
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      # - name: Test
      #   run: npm run test
      #   shell: bash
